### ISSUE TITLE
Building errors [bug]

### ISSUE THREAD

**Issue by ArtichOwO** [CacahueteSansSel/leterminal#1]
Your project seems awesome, but I can't build it (I tried with let in the apps folder, but there's a lot of .h missing and other errors), so if you could put some building instructions (I saw a todo in the readme, but nobody can test it without these)
I'd love to contribute, so thanks in advance ^^

**Comment by CacahueteSansSel** [comment]
I've just added instructions on how to build it. I will test if I can compile it with a fresh instance of Epsilon and I will close this as soon as it's working.

**Comment by ArtichOwO** [comment]
Thanks a lot !

**Comment by CacahueteSansSel** [comment]
Indeed I've found a lot of errors regarding the local commands (it is a missing header file), I am fixing everything up.

**Comment by CacahueteSansSel** [comment]
I think I fixed everything. I leave the issue opened in case of build failures you may encounter. Thanks a lot !

**Comment by ArtichOwO** [comment]
(idk if I should open a new issue or not)
```
apps/terminal/termscreen.h:497:38: error: character too large for enclosing character literal type
        LMAP(Ion::Keyboard::Key::Pi, 'π', '=', 'j', 'J');
                                     ^
apps/terminal/termscreen.h:497:38: error: character too large for enclosing character literal type
```
I tried to change `π` to `pi`, and there's no more errors (for now)

After that, I got this error :
```
apps/terminal/terminal.cpp:13:10: fatal error: 'local_commands.h' file not found
#include "local_commands.h"
         ^~~~~~~~~~~~~~~~~~
```
When looking in the `.gitignore` file, I saw `local_commands.h`, maybe you forgot to remove it ?

**Comment by CacahueteSansSel** [comment]
Yes, I forgot to delete this old file from the `.gitignore`. And for the issue with `pi`, this is because the `π` character seems to be higher than 1 byte in size. I am fixing that. (I'm also adding a way to add commands easily from this file)

**Comment by ArtichOwO** [comment]
That's great, thanks !

**Comment by CacahueteSansSel** [comment]
I've made a commit, I hope this is fixed, let me know if it compiles.

**Comment by ArtichOwO** [comment]
It works super fine!! You nailed it, the interface is great :D
Again, thanks a lot!!

(gotta fork this x3)

**Comment by CacahueteSansSel** [comment]
Thanks a lot too ! ;)
Have fun with this little project !
